.\" This is a comment
.\" Contact Owen@thelinuxblog.com
.TH man 1 "21 June 2009" ".1" "Man Page Example"
.SH NAME
mwt
.SH SYNOPSIS
mwt [OPTION] 
.SH DESCRIPTION
mwt is a simple program that attempt to re-create Shakespearean sonnet 116 with the generation of random characters. By default MWT does not generate any output.
.SH OPTIONS
.IP -v
Display number of attempts made.
.IP -vv
Display the number of attempts made as well as the randomly generated text.
.SH SEE ALSO
python3(1)
.SH BUGS
No known bugs.
.SH AUTHOR
"Super" Nathan Weber (supernathansunshine@gmail.com)

