
.TH USAGE: "1" "May 2013" "Usage: mwt [options]" "User Commands"
.SH NAME
sddm -  a usefull stress testing tool with a ultimate distributed computing goal
.SH DESCRIPTION
mwt is a simple program that attempt to re-create Shakespearean sonnet 116 with the generation of random characters. By default MWT does not generate any output.
.SH SYNOPSIS
mwt [OPTION] 
.SH OPTIONS
.IP -v
Display number of attempts made.
.IP -vv
Display the number of attempts made as well as the randomly generated text.
.SH SEE ALSO
python3(1)
.SH BUGS
No known bugs.
.SH AUTHOR
"Super" Nathan Weber (supernathansunshine@gmail.com)

